version: '3'
services:
  postgres:
    image: postgres:14.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - D:/Hromau/vol/postgresy:/var/lib/postgresql/data