server:
  port: 8080

spring:

  liquibase:
    enabled: true
    drop-first: false
    change-log: /db/changelog/database-monitoring-service-changelog.xml
    default-schema: monitoring_service
    liquibase-schema: settings

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

permission:
  unauthorized:
    urls:
      - /api/v1/auth/register
      - /api/v1/auth/login
      - /swagger-ui/**
      - /v3/api-docs/**
  admin:
    urls:
      - /api/v1/meter/reading/all

validator:
  credential:
    loginPattern: ^[a-zA-Z0-9._-]{3,15}$
    passwordPattern: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;',?/*~$^+=<>]).{8,20}$

meter:
  system:
    path:

springdoc:
  api-docs:
    enabled: true
    path: '/v3/api-docs'
  swagger-ui:
    path: '/swagger-ui.html'
    doc-expansion: none
    disable-swagger-default-url: true

